twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/custom.html.twig']
    globals:
        showcase_website_url: '%showcase_website_url%'
        env: '%env(APP_ENV)%'
        icons:
            home: 'fa-place-of-worship'
            source: 'fa-ankh'
            attestation: 'fa-file-alt'
            element: 'fa-atom'
            bibliography: 'fa-book-open'
            queries: 'fa-search'