version: '3.7'

volumes:
    pgdata:

services:
    nginx:
        build: ./.docker/nginx
        depends_on:
            - php
        volumes:
            # Logs
            - ./logs/nginx:/var/log/nginx:delegated
            # Code
            - .:/var/www/html:delegated
        ports:
            - "80:80"

    php:
        build: ./.docker/php
        working_dir: /var/www/html/
        depends_on:
            - db
        volumes:
            # Logs
            - ./logs/symfony:/var/www/html/var/log:delegated
            # Code
            - .:/var/www/html:delegated
            # Vendor délégués au container
            - ./vendor:/var/www/html/vendor:delegated
        ports:
            - "9000:9001"

    db:
        build: ./.docker/pgsql
        volumes:
            - pgdata:/var/lib/postgresql/data:delegated
        environment:
            # Nécessaire
            # - POSTGRES_USER=polytheisms
            # - POSTGRES_PASSWORD=polytheisms
            # - POSTGRES_DB=polytheisms
            # - DEFAULT_COLLATION="fr_FR.UTF-8"
            # - DEFAULT_ENCODING="UTF8"
            # - DEFAULT_CTYPE="fr_FR.UTF-8"
            - ALLOW_IP_RANGE="0.0.0.0/0"
        ports:
            # local 5432:5432 remote
            - 5432:5432

    yarn:
        image: node:13.2
        depends_on:
            - php
        working_dir: /var/www/html/
        command: sh -c "npm install && npm run watch"
        volumes:
            # Code
            - .:/var/www/html:delegated
            # node_modules et build sont délégués au container
            - ./node_modules:/var/www/html/node_modules:delegated
            - ./public/build:/var/www/html/public/build:delegated

    adminer:
        image: adminer
        depends_on:
            - php
            - db
        ports:
            # local 8080:8080 remote
            - 8080:8080
