# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    showcase_website_url: https://map-polytheisms.huma-num.fr/
    duree_verrou: 30 #durée des verrous sur les données (en minutes)
    from_email: map.polytheisms@gmail.com
    from_name: "ERC-MAP-BD"
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    open_access: false
    geo.app_url_fr: "https://geoapps.huma-num.fr/adws/app/8cc4e1b9-3a92-11e9-8702-e571f836e404/"
    geo.app_url_en: "https://geoapps.huma-num.fr/adws/app/6b2d0f72-83ac-11ea-9fab-cdd8796420d3/"
    geo.function_source_fr: "1e143ce6-6ce3-11ea-90e3-f7ccf6c80337"
    geo.function_source_en: "3b0dbd72-b252-11ea-999a-b1f174524d4a"
    geo.function_attestation_fr: "535b801c-6ce4-11ea-90e3-f7ccf6c80337"
    geo.function_attestation_en: "f8241cf7-b252-11ea-999a-b1f174524d4a"
    geo.function_element_fr: "d7d0e69f-7014-11ea-aeaa-a31c099aad1e"
    geo.function_element_en: "aae3160d-b253-11ea-999a-b1f174524d4a"
    pdf_path: "%kernel.project_dir%/public/build/files"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $dureeVerrou: '%duree_verrou%'
            $fromEmail: '%from_email%'
            $fromName: '%from_name%'
            $openAccess: '%open_access%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    App\EventSubscriber\LocaleSubscriber:
        arguments: ['%kernel.default_locale%']

    App\EventListener\ClearOrphanLocationsSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\EventListener\DatabaseActivitySubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\EventListener\RedirectUserListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments:
            - "@security.token_storage"
            - "@router"