<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190517093907 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE activite_agent_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE agent_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE agentivite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE attestation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE auteur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE biblio_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_materiau_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_occasion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_source_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE categorie_support_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE chercheur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE datation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE entite_politique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE etat_fiche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE formule_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE genre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE genre_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE grande_region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE langue_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE localisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE materiau_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE materiel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nature_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nombre_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE occasion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pratique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE projet_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE q_fonction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE q_topographie_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE source_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sous_region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE statut_affiche_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE titre_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE traduction_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_source_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_support_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE verrou_entite_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE activite_agent (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE agent (id INT NOT NULL, id_attestation INT DEFAULT NULL, localisation_id INT DEFAULT NULL, designation TEXT DEFAULT NULL, est_localisee BOOLEAN DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_268B9C9D2A7C0BC8 ON agent (id_attestation)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_268B9C9DC68BE09C ON agent (localisation_id)');
        $this->addSql('CREATE TABLE agent_statut (id_agent INT NOT NULL, id_statut INT NOT NULL, PRIMARY KEY(id_agent, id_statut))');
        $this->addSql('CREATE INDEX IDX_BB83A799C80EDDAD ON agent_statut (id_agent)');
        $this->addSql('CREATE INDEX IDX_BB83A799C3534552 ON agent_statut (id_statut)');
        $this->addSql('CREATE TABLE agent_nature (id_agent INT NOT NULL, id_nature INT NOT NULL, PRIMARY KEY(id_agent, id_nature))');
        $this->addSql('CREATE INDEX IDX_EF3FD581C80EDDAD ON agent_nature (id_agent)');
        $this->addSql('CREATE INDEX IDX_EF3FD58197EF374A ON agent_nature (id_nature)');
        $this->addSql('CREATE TABLE agent_genre (id_agent INT NOT NULL, id_genre INT NOT NULL, PRIMARY KEY(id_agent, id_genre))');
        $this->addSql('CREATE INDEX IDX_BAFE1B80C80EDDAD ON agent_genre (id_agent)');
        $this->addSql('CREATE INDEX IDX_BAFE1B806DD572C8 ON agent_genre (id_genre)');
        $this->addSql('CREATE TABLE agent_activite (id_agent INT NOT NULL, id_activite INT NOT NULL, PRIMARY KEY(id_agent, id_activite))');
        $this->addSql('CREATE INDEX IDX_8EA44C81C80EDDAD ON agent_activite (id_agent)');
        $this->addSql('CREATE INDEX IDX_8EA44C81E8AEB980 ON agent_activite (id_activite)');
        $this->addSql('CREATE TABLE agent_agentivite (id_agent INT NOT NULL, id_agentivite INT NOT NULL, PRIMARY KEY(id_agent, id_agentivite))');
        $this->addSql('CREATE INDEX IDX_AC21DF1CC80EDDAD ON agent_agentivite (id_agent)');
        $this->addSql('CREATE INDEX IDX_AC21DF1C78ED8EC4 ON agent_agentivite (id_agentivite)');
        $this->addSql('CREATE TABLE agentivite (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE attestation (id INT NOT NULL, id_source INT NOT NULL, id_etat_fiche INT DEFAULT NULL, verrou_id INT DEFAULT NULL, datation_id INT DEFAULT NULL, localisation_id INT DEFAULT NULL, user_creation_id INT NOT NULL, user_edition_id INT NOT NULL, passage VARCHAR(255) DEFAULT NULL, extrait_sans_restitution TEXT DEFAULT NULL, extrait_avec_restitution TEXT DEFAULT NULL, translitteration TEXT DEFAULT NULL, fiabilite_attestation SMALLINT DEFAULT NULL, prose BOOLEAN DEFAULT \'true\', poesie BOOLEAN DEFAULT \'false\', est_datee BOOLEAN DEFAULT NULL, est_localisee BOOLEAN DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, traduire_fr BOOLEAN DEFAULT NULL, traduire_en BOOLEAN DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_326EC63F79BDCA9E ON attestation (id_source)');
        $this->addSql('CREATE INDEX IDX_326EC63FAF0E6016 ON attestation (id_etat_fiche)');
        $this->addSql('CREATE INDEX IDX_326EC63F1E25C1F6 ON attestation (verrou_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_326EC63F6AE6DFC0 ON attestation (datation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_326EC63FC68BE09C ON attestation (localisation_id)');
        $this->addSql('CREATE INDEX IDX_326EC63F9DE46F0F ON attestation (user_creation_id)');
        $this->addSql('CREATE INDEX IDX_326EC63FD34FDCB2 ON attestation (user_edition_id)');
        $this->addSql('CREATE TABLE attestation_pratique (id_attestation INT NOT NULL, id_pratique INT NOT NULL, PRIMARY KEY(id_attestation, id_pratique))');
        $this->addSql('CREATE INDEX IDX_F048224C2A7C0BC8 ON attestation_pratique (id_attestation)');
        $this->addSql('CREATE INDEX IDX_F048224C51295B14 ON attestation_pratique (id_pratique)');
        $this->addSql('CREATE TABLE attestation_occasion (id_attestation INT NOT NULL, id_occasion INT NOT NULL, PRIMARY KEY(id_attestation, id_occasion))');
        $this->addSql('CREATE INDEX IDX_7BDC49282A7C0BC8 ON attestation_occasion (id_attestation)');
        $this->addSql('CREATE INDEX IDX_7BDC4928DABD3070 ON attestation_occasion (id_occasion)');
        $this->addSql('CREATE TABLE attestation_materiel (id_attestation INT NOT NULL, id_materiel INT NOT NULL, quantite SMALLINT DEFAULT NULL, PRIMARY KEY(id_attestation, id_materiel))');
        $this->addSql('CREATE INDEX IDX_E968255C2A7C0BC8 ON attestation_materiel (id_attestation)');
        $this->addSql('CREATE INDEX IDX_E968255C48095C04 ON attestation_materiel (id_materiel)');
        $this->addSql('CREATE TABLE auteur (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE biblio (id INT NOT NULL, titre_abrege VARCHAR(255) DEFAULT NULL, titre_complet TEXT DEFAULT NULL, annee SMALLINT DEFAULT NULL, auteur_biblio VARCHAR(255) DEFAULT NULL, est_corpus BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_element (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_materiau (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_materiel (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_occasion (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_source (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE categorie_support (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE chercheur (id INT NOT NULL, prenom_nom VARCHAR(255) NOT NULL, username VARCHAR(150) NOT NULL, institution VARCHAR(250) DEFAULT NULL, mail VARCHAR(250) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, preference_langue VARCHAR(2) DEFAULT NULL, date_ajout DATE DEFAULT NULL, role VARCHAR(50) DEFAULT NULL, reset_token VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contient_element (position_element SMALLINT NOT NULL, id_attestation INT NOT NULL, id_element INT NOT NULL, id_categorie_element INT DEFAULT NULL, id_genre_element INT DEFAULT NULL, id_nombre_element INT DEFAULT NULL, etat_morphologique VARCHAR(255) DEFAULT NULL, suffixe BOOLEAN DEFAULT NULL, en_contexte TEXT DEFAULT NULL, PRIMARY KEY(id_attestation, id_element, position_element))');
        $this->addSql('CREATE INDEX IDX_71BC92312A7C0BC8 ON contient_element (id_attestation)');
        $this->addSql('CREATE INDEX IDX_71BC92319FDDF749 ON contient_element (id_element)');
        $this->addSql('CREATE INDEX IDX_71BC9231EFF4988C ON contient_element (id_categorie_element)');
        $this->addSql('CREATE INDEX IDX_71BC9231C4ED1CA4 ON contient_element (id_genre_element)');
        $this->addSql('CREATE INDEX IDX_71BC9231883FA27F ON contient_element (id_nombre_element)');
        $this->addSql('CREATE TABLE datation (id INT NOT NULL, post_quem SMALLINT DEFAULT NULL, ante_quem SMALLINT DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE element (id INT NOT NULL, id_nature_element INT DEFAULT NULL, verrou_id INT DEFAULT NULL, localisation_id INT DEFAULT NULL, user_creation_id INT NOT NULL, user_edition_id INT NOT NULL, etat_absolu VARCHAR(255) DEFAULT NULL, beta_code VARCHAR(255) DEFAULT NULL, a_reference BOOLEAN DEFAULT NULL, est_localisee BOOLEAN DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, traduire_fr BOOLEAN DEFAULT NULL, traduire_en BOOLEAN DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_41405E3964A5A8EA ON element (id_nature_element)');
        $this->addSql('CREATE INDEX IDX_41405E391E25C1F6 ON element (verrou_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41405E39C68BE09C ON element (localisation_id)');
        $this->addSql('CREATE INDEX IDX_41405E399DE46F0F ON element (user_creation_id)');
        $this->addSql('CREATE INDEX IDX_41405E39D34FDCB2 ON element (user_edition_id)');
        $this->addSql('CREATE TABLE element_categorie (id_element INT NOT NULL, id_categorie_element INT NOT NULL, PRIMARY KEY(id_element, id_categorie_element))');
        $this->addSql('CREATE INDEX IDX_E176F81F9FDDF749 ON element_categorie (id_element)');
        $this->addSql('CREATE INDEX IDX_E176F81FEFF4988C ON element_categorie (id_categorie_element)');
        $this->addSql('CREATE TABLE theonymes_implicites (id_parent INT NOT NULL, id_enfant INT NOT NULL, PRIMARY KEY(id_parent, id_enfant))');
        $this->addSql('CREATE INDEX IDX_F6A451291BB9D5A2 ON theonymes_implicites (id_parent)');
        $this->addSql('CREATE INDEX IDX_F6A451291280B94F ON theonymes_implicites (id_enfant)');
        $this->addSql('CREATE TABLE theonymes_construits (id_parent INT NOT NULL, id_enfant INT NOT NULL, PRIMARY KEY(id_parent, id_enfant))');
        $this->addSql('CREATE INDEX IDX_88F7723B1BB9D5A2 ON theonymes_construits (id_parent)');
        $this->addSql('CREATE INDEX IDX_88F7723B1280B94F ON theonymes_construits (id_enfant)');
        $this->addSql('CREATE TABLE element_biblio (id_element INT NOT NULL, id_biblio INT NOT NULL, reference_element VARCHAR(255) DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id_element, id_biblio))');
        $this->addSql('CREATE INDEX IDX_501BB2B19FDDF749 ON element_biblio (id_element)');
        $this->addSql('CREATE INDEX IDX_501BB2B1FF3B0EC8 ON element_biblio (id_biblio)');
        $this->addSql('CREATE TABLE entite_politique (id INT NOT NULL, numero_iacp SMALLINT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE etat_fiche (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE formule (id INT NOT NULL, attestation_id INT DEFAULT NULL, user_creation_id INT NOT NULL, formule TEXT NOT NULL, position_formule SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_605C9C987EDC5B38 ON formule (attestation_id)');
        $this->addSql('CREATE INDEX IDX_605C9C989DE46F0F ON formule (user_creation_id)');
        $this->addSql('CREATE TABLE genre (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE genre_element (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE grande_region (id INT NOT NULL, geom geometry(MULTIPOLYGON, 4326) DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE langue (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE localisation (id INT NOT NULL, entite_politique INT DEFAULT NULL, grande_region_id INT DEFAULT NULL, sous_region_id INT DEFAULT NULL, pleiades_ville INT DEFAULT NULL, nom_ville VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, pleiades_site INT DEFAULT NULL, nom_site VARCHAR(255) DEFAULT NULL, reel BOOLEAN DEFAULT NULL, geom geometry(POINT, 4326) DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BFD3CE8FDEC11ACA ON localisation (entite_politique)');
        $this->addSql('CREATE INDEX IDX_BFD3CE8F5FF94818 ON localisation (grande_region_id)');
        $this->addSql('CREATE INDEX IDX_BFD3CE8F832FEA1A ON localisation (sous_region_id)');
        $this->addSql('CREATE TABLE localisation_q_topographie (id_localisation INT NOT NULL, id_q_topographie INT NOT NULL, PRIMARY KEY(id_localisation, id_q_topographie))');
        $this->addSql('CREATE INDEX IDX_C3D418BE9C12BBFD ON localisation_q_topographie (id_localisation)');
        $this->addSql('CREATE INDEX IDX_C3D418BE71B07B4 ON localisation_q_topographie (id_q_topographie)');
        $this->addSql('CREATE TABLE localisation_q_fonction (id_localisation INT NOT NULL, id_q_fonction INT NOT NULL, PRIMARY KEY(id_localisation, id_q_fonction))');
        $this->addSql('CREATE INDEX IDX_F8B0B4679C12BBFD ON localisation_q_fonction (id_localisation)');
        $this->addSql('CREATE INDEX IDX_F8B0B4679E428274 ON localisation_q_fonction (id_q_fonction)');
        $this->addSql('CREATE TABLE materiau (id INT NOT NULL, categorie_materiau_id INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_18D5DD5511E79273 ON materiau (categorie_materiau_id)');
        $this->addSql('CREATE TABLE materiel (id INT NOT NULL, categorie_materiel_id INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_18D2B091C9762CA6 ON materiel (categorie_materiel_id)');
        $this->addSql('CREATE TABLE nature (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nature_element (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nombre_element (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE occasion (id INT NOT NULL, categorie_occasion_id INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8A66DCE59FCABF86 ON occasion (categorie_occasion_id)');
        $this->addSql('CREATE TABLE pratique (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE projet (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE projet_chercheur (id_projet INT NOT NULL, id_chercheur INT NOT NULL, PRIMARY KEY(id_projet, id_chercheur))');
        $this->addSql('CREATE INDEX IDX_BE2C7C8476222944 ON projet_chercheur (id_projet)');
        $this->addSql('CREATE INDEX IDX_BE2C7C841DE72777 ON projet_chercheur (id_chercheur)');
        $this->addSql('CREATE TABLE q_fonction (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE q_topographie (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE source (id INT NOT NULL, titre_principal_id INT DEFAULT NULL, type_support_id INT DEFAULT NULL, categorie_support_id INT DEFAULT NULL, materiau_id INT DEFAULT NULL, categorie_materiau_id INT DEFAULT NULL, type_source_id INT DEFAULT NULL, categorie_source_id INT DEFAULT NULL, localisation_decouverte_id INT DEFAULT NULL, localisation_origine_id INT DEFAULT NULL, id_projet INT DEFAULT NULL, verrou_id INT DEFAULT NULL, datation_id INT DEFAULT NULL, user_creation_id INT NOT NULL, user_edition_id INT NOT NULL, iconographie BOOLEAN DEFAULT NULL, url_texte TEXT DEFAULT NULL, url_image TEXT DEFAULT NULL, in_situ BOOLEAN DEFAULT NULL, fiabilite_localisation SMALLINT DEFAULT NULL, fiabilite_datation SMALLINT DEFAULT NULL, est_datee BOOLEAN DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, version INT NOT NULL, traduire_fr BOOLEAN DEFAULT NULL, traduire_en BOOLEAN DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5F8A7F7381C7EF2 ON source (titre_principal_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F731E166220 ON source (type_support_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F739DDC7EA9 ON source (categorie_support_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F73CE19B47A ON source (materiau_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F7311E79273 ON source (categorie_materiau_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F7321FA5D71 ON source (type_source_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F7338631366 ON source (categorie_source_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F73343700E0 ON source (localisation_decouverte_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F73C3FF2F4A ON source (localisation_origine_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F7376222944 ON source (id_projet)');
        $this->addSql('CREATE INDEX IDX_5F8A7F731E25C1F6 ON source (verrou_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5F8A7F736AE6DFC0 ON source (datation_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F739DE46F0F ON source (user_creation_id)');
        $this->addSql('CREATE INDEX IDX_5F8A7F73D34FDCB2 ON source (user_edition_id)');
        $this->addSql('CREATE TABLE source_auteur (id_source INT NOT NULL, id_auteur INT NOT NULL, PRIMARY KEY(id_source, id_auteur))');
        $this->addSql('CREATE INDEX IDX_B3A594A679BDCA9E ON source_auteur (id_source)');
        $this->addSql('CREATE INDEX IDX_B3A594A6236D04AD ON source_auteur (id_auteur)');
        $this->addSql('CREATE TABLE source_langue (id_source INT NOT NULL, id_langue INT NOT NULL, PRIMARY KEY(id_source, id_langue))');
        $this->addSql('CREATE INDEX IDX_25A8506879BDCA9E ON source_langue (id_source)');
        $this->addSql('CREATE INDEX IDX_25A85068B560C063 ON source_langue (id_langue)');
        $this->addSql('CREATE TABLE source_biblio (id_source INT NOT NULL, id_biblio INT NOT NULL, edition_principale BOOLEAN DEFAULT NULL, reference_source VARCHAR(255) DEFAULT NULL, commentaire_fr TEXT DEFAULT NULL, commentaire_en TEXT DEFAULT NULL, PRIMARY KEY(id_source, id_biblio))');
        $this->addSql('CREATE INDEX IDX_6FF39EC379BDCA9E ON source_biblio (id_source)');
        $this->addSql('CREATE INDEX IDX_6FF39EC3FF3B0EC8 ON source_biblio (id_biblio)');
        $this->addSql('CREATE TABLE sous_region (id INT NOT NULL, grande_region_id INT DEFAULT NULL, geom geometry(POINT, 4326) DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DF7D03815FF94818 ON sous_region (grande_region_id)');
        $this->addSql('CREATE TABLE statut_affiche (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE titre (id INT NOT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE titre_auteur (id_titre INT NOT NULL, id_auteur INT NOT NULL, PRIMARY KEY(id_titre, id_auteur))');
        $this->addSql('CREATE INDEX IDX_AFF93D8A11F20684 ON titre_auteur (id_titre)');
        $this->addSql('CREATE INDEX IDX_AFF93D8A236D04AD ON titre_auteur (id_auteur)');
        $this->addSql('CREATE TABLE traduction_element (id INT NOT NULL, id_element INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7F7FF2499FDDF749 ON traduction_element (id_element)');
        $this->addSql('CREATE TABLE type_source (id INT NOT NULL, categorie_source_id INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7C5D144B38631366 ON type_source (categorie_source_id)');
        $this->addSql('CREATE TABLE type_support (id INT NOT NULL, categorie_support_id INT DEFAULT NULL, nom_fr VARCHAR(255) DEFAULT NULL, nom_en VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A82584509DDC7EA9 ON type_support (categorie_support_id)');
        $this->addSql('CREATE TABLE verrou_entite (id INT NOT NULL, user_creation_id INT NOT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E87AB10F9DE46F0F ON verrou_entite (user_creation_id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D2A7C0BC8 FOREIGN KEY (id_attestation) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9DC68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_statut ADD CONSTRAINT FK_BB83A799C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_statut ADD CONSTRAINT FK_BB83A799C3534552 FOREIGN KEY (id_statut) REFERENCES statut_affiche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_nature ADD CONSTRAINT FK_EF3FD581C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_nature ADD CONSTRAINT FK_EF3FD58197EF374A FOREIGN KEY (id_nature) REFERENCES nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_genre ADD CONSTRAINT FK_BAFE1B80C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_genre ADD CONSTRAINT FK_BAFE1B806DD572C8 FOREIGN KEY (id_genre) REFERENCES genre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_activite ADD CONSTRAINT FK_8EA44C81C80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_activite ADD CONSTRAINT FK_8EA44C81E8AEB980 FOREIGN KEY (id_activite) REFERENCES activite_agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_agentivite ADD CONSTRAINT FK_AC21DF1CC80EDDAD FOREIGN KEY (id_agent) REFERENCES agent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE agent_agentivite ADD CONSTRAINT FK_AC21DF1C78ED8EC4 FOREIGN KEY (id_agentivite) REFERENCES agentivite (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F79BDCA9E FOREIGN KEY (id_source) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63FAF0E6016 FOREIGN KEY (id_etat_fiche) REFERENCES etat_fiche (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F1E25C1F6 FOREIGN KEY (verrou_id) REFERENCES verrou_entite (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F6AE6DFC0 FOREIGN KEY (datation_id) REFERENCES datation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63FC68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63F9DE46F0F FOREIGN KEY (user_creation_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation ADD CONSTRAINT FK_326EC63FD34FDCB2 FOREIGN KEY (user_edition_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_pratique ADD CONSTRAINT FK_F048224C2A7C0BC8 FOREIGN KEY (id_attestation) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_pratique ADD CONSTRAINT FK_F048224C51295B14 FOREIGN KEY (id_pratique) REFERENCES pratique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_occasion ADD CONSTRAINT FK_7BDC49282A7C0BC8 FOREIGN KEY (id_attestation) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_occasion ADD CONSTRAINT FK_7BDC4928DABD3070 FOREIGN KEY (id_occasion) REFERENCES occasion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_materiel ADD CONSTRAINT FK_E968255C2A7C0BC8 FOREIGN KEY (id_attestation) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attestation_materiel ADD CONSTRAINT FK_E968255C48095C04 FOREIGN KEY (id_materiel) REFERENCES materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contient_element ADD CONSTRAINT FK_71BC92312A7C0BC8 FOREIGN KEY (id_attestation) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contient_element ADD CONSTRAINT FK_71BC92319FDDF749 FOREIGN KEY (id_element) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contient_element ADD CONSTRAINT FK_71BC9231EFF4988C FOREIGN KEY (id_categorie_element) REFERENCES categorie_element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contient_element ADD CONSTRAINT FK_71BC9231C4ED1CA4 FOREIGN KEY (id_genre_element) REFERENCES genre_element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contient_element ADD CONSTRAINT FK_71BC9231883FA27F FOREIGN KEY (id_nombre_element) REFERENCES nombre_element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E3964A5A8EA FOREIGN KEY (id_nature_element) REFERENCES nature_element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E391E25C1F6 FOREIGN KEY (verrou_id) REFERENCES verrou_entite (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E39C68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E399DE46F0F FOREIGN KEY (user_creation_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element ADD CONSTRAINT FK_41405E39D34FDCB2 FOREIGN KEY (user_edition_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_categorie ADD CONSTRAINT FK_E176F81F9FDDF749 FOREIGN KEY (id_element) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_categorie ADD CONSTRAINT FK_E176F81FEFF4988C FOREIGN KEY (id_categorie_element) REFERENCES categorie_element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE theonymes_implicites ADD CONSTRAINT FK_F6A451291BB9D5A2 FOREIGN KEY (id_parent) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE theonymes_implicites ADD CONSTRAINT FK_F6A451291280B94F FOREIGN KEY (id_enfant) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE theonymes_construits ADD CONSTRAINT FK_88F7723B1BB9D5A2 FOREIGN KEY (id_parent) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE theonymes_construits ADD CONSTRAINT FK_88F7723B1280B94F FOREIGN KEY (id_enfant) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_biblio ADD CONSTRAINT FK_501BB2B19FDDF749 FOREIGN KEY (id_element) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE element_biblio ADD CONSTRAINT FK_501BB2B1FF3B0EC8 FOREIGN KEY (id_biblio) REFERENCES biblio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formule ADD CONSTRAINT FK_605C9C987EDC5B38 FOREIGN KEY (attestation_id) REFERENCES attestation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formule ADD CONSTRAINT FK_605C9C989DE46F0F FOREIGN KEY (user_creation_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FDEC11ACA FOREIGN KEY (entite_politique) REFERENCES entite_politique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8F5FF94818 FOREIGN KEY (grande_region_id) REFERENCES grande_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8F832FEA1A FOREIGN KEY (sous_region_id) REFERENCES sous_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation_q_topographie ADD CONSTRAINT FK_C3D418BE9C12BBFD FOREIGN KEY (id_localisation) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation_q_topographie ADD CONSTRAINT FK_C3D418BE71B07B4 FOREIGN KEY (id_q_topographie) REFERENCES q_topographie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation_q_fonction ADD CONSTRAINT FK_F8B0B4679C12BBFD FOREIGN KEY (id_localisation) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation_q_fonction ADD CONSTRAINT FK_F8B0B4679E428274 FOREIGN KEY (id_q_fonction) REFERENCES q_fonction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE materiau ADD CONSTRAINT FK_18D5DD5511E79273 FOREIGN KEY (categorie_materiau_id) REFERENCES categorie_materiau (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE materiel ADD CONSTRAINT FK_18D2B091C9762CA6 FOREIGN KEY (categorie_materiel_id) REFERENCES categorie_materiel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE59FCABF86 FOREIGN KEY (categorie_occasion_id) REFERENCES categorie_occasion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_chercheur ADD CONSTRAINT FK_BE2C7C8476222944 FOREIGN KEY (id_projet) REFERENCES projet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE projet_chercheur ADD CONSTRAINT FK_BE2C7C841DE72777 FOREIGN KEY (id_chercheur) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7381C7EF2 FOREIGN KEY (titre_principal_id) REFERENCES titre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F731E166220 FOREIGN KEY (type_support_id) REFERENCES type_support (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F739DDC7EA9 FOREIGN KEY (categorie_support_id) REFERENCES categorie_support (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73CE19B47A FOREIGN KEY (materiau_id) REFERENCES materiau (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7311E79273 FOREIGN KEY (categorie_materiau_id) REFERENCES categorie_materiau (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7321FA5D71 FOREIGN KEY (type_source_id) REFERENCES type_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7338631366 FOREIGN KEY (categorie_source_id) REFERENCES categorie_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73343700E0 FOREIGN KEY (localisation_decouverte_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73C3FF2F4A FOREIGN KEY (localisation_origine_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F7376222944 FOREIGN KEY (id_projet) REFERENCES projet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F731E25C1F6 FOREIGN KEY (verrou_id) REFERENCES verrou_entite (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F736AE6DFC0 FOREIGN KEY (datation_id) REFERENCES datation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F739DE46F0F FOREIGN KEY (user_creation_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73D34FDCB2 FOREIGN KEY (user_edition_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_auteur ADD CONSTRAINT FK_B3A594A679BDCA9E FOREIGN KEY (id_source) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_auteur ADD CONSTRAINT FK_B3A594A6236D04AD FOREIGN KEY (id_auteur) REFERENCES auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_langue ADD CONSTRAINT FK_25A8506879BDCA9E FOREIGN KEY (id_source) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_langue ADD CONSTRAINT FK_25A85068B560C063 FOREIGN KEY (id_langue) REFERENCES langue (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_biblio ADD CONSTRAINT FK_6FF39EC379BDCA9E FOREIGN KEY (id_source) REFERENCES source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE source_biblio ADD CONSTRAINT FK_6FF39EC3FF3B0EC8 FOREIGN KEY (id_biblio) REFERENCES biblio (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sous_region ADD CONSTRAINT FK_DF7D03815FF94818 FOREIGN KEY (grande_region_id) REFERENCES grande_region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE titre_auteur ADD CONSTRAINT FK_AFF93D8A11F20684 FOREIGN KEY (id_titre) REFERENCES titre (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE titre_auteur ADD CONSTRAINT FK_AFF93D8A236D04AD FOREIGN KEY (id_auteur) REFERENCES auteur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE traduction_element ADD CONSTRAINT FK_7F7FF2499FDDF749 FOREIGN KEY (id_element) REFERENCES element (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_source ADD CONSTRAINT FK_7C5D144B38631366 FOREIGN KEY (categorie_source_id) REFERENCES categorie_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_support ADD CONSTRAINT FK_A82584509DDC7EA9 FOREIGN KEY (categorie_support_id) REFERENCES categorie_support (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE verrou_entite ADD CONSTRAINT FK_E87AB10F9DE46F0F FOREIGN KEY (user_creation_id) REFERENCES chercheur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE agent_activite DROP CONSTRAINT FK_8EA44C81E8AEB980');
        $this->addSql('ALTER TABLE agent_statut DROP CONSTRAINT FK_BB83A799C80EDDAD');
        $this->addSql('ALTER TABLE agent_nature DROP CONSTRAINT FK_EF3FD581C80EDDAD');
        $this->addSql('ALTER TABLE agent_genre DROP CONSTRAINT FK_BAFE1B80C80EDDAD');
        $this->addSql('ALTER TABLE agent_activite DROP CONSTRAINT FK_8EA44C81C80EDDAD');
        $this->addSql('ALTER TABLE agent_agentivite DROP CONSTRAINT FK_AC21DF1CC80EDDAD');
        $this->addSql('ALTER TABLE agent_agentivite DROP CONSTRAINT FK_AC21DF1C78ED8EC4');
        $this->addSql('ALTER TABLE agent DROP CONSTRAINT FK_268B9C9D2A7C0BC8');
        $this->addSql('ALTER TABLE attestation_pratique DROP CONSTRAINT FK_F048224C2A7C0BC8');
        $this->addSql('ALTER TABLE attestation_occasion DROP CONSTRAINT FK_7BDC49282A7C0BC8');
        $this->addSql('ALTER TABLE attestation_materiel DROP CONSTRAINT FK_E968255C2A7C0BC8');
        $this->addSql('ALTER TABLE contient_element DROP CONSTRAINT FK_71BC92312A7C0BC8');
        $this->addSql('ALTER TABLE formule DROP CONSTRAINT FK_605C9C987EDC5B38');
        $this->addSql('ALTER TABLE source_auteur DROP CONSTRAINT FK_B3A594A6236D04AD');
        $this->addSql('ALTER TABLE titre_auteur DROP CONSTRAINT FK_AFF93D8A236D04AD');
        $this->addSql('ALTER TABLE element_biblio DROP CONSTRAINT FK_501BB2B1FF3B0EC8');
        $this->addSql('ALTER TABLE source_biblio DROP CONSTRAINT FK_6FF39EC3FF3B0EC8');
        $this->addSql('ALTER TABLE contient_element DROP CONSTRAINT FK_71BC9231EFF4988C');
        $this->addSql('ALTER TABLE element_categorie DROP CONSTRAINT FK_E176F81FEFF4988C');
        $this->addSql('ALTER TABLE materiau DROP CONSTRAINT FK_18D5DD5511E79273');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7311E79273');
        $this->addSql('ALTER TABLE materiel DROP CONSTRAINT FK_18D2B091C9762CA6');
        $this->addSql('ALTER TABLE occasion DROP CONSTRAINT FK_8A66DCE59FCABF86');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7338631366');
        $this->addSql('ALTER TABLE type_source DROP CONSTRAINT FK_7C5D144B38631366');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F739DDC7EA9');
        $this->addSql('ALTER TABLE type_support DROP CONSTRAINT FK_A82584509DDC7EA9');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F9DE46F0F');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63FD34FDCB2');
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E399DE46F0F');
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E39D34FDCB2');
        $this->addSql('ALTER TABLE formule DROP CONSTRAINT FK_605C9C989DE46F0F');
        $this->addSql('ALTER TABLE projet_chercheur DROP CONSTRAINT FK_BE2C7C841DE72777');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F739DE46F0F');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73D34FDCB2');
        $this->addSql('ALTER TABLE verrou_entite DROP CONSTRAINT FK_E87AB10F9DE46F0F');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F6AE6DFC0');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F736AE6DFC0');
        $this->addSql('ALTER TABLE contient_element DROP CONSTRAINT FK_71BC92319FDDF749');
        $this->addSql('ALTER TABLE element_categorie DROP CONSTRAINT FK_E176F81F9FDDF749');
        $this->addSql('ALTER TABLE theonymes_implicites DROP CONSTRAINT FK_F6A451291BB9D5A2');
        $this->addSql('ALTER TABLE theonymes_implicites DROP CONSTRAINT FK_F6A451291280B94F');
        $this->addSql('ALTER TABLE theonymes_construits DROP CONSTRAINT FK_88F7723B1BB9D5A2');
        $this->addSql('ALTER TABLE theonymes_construits DROP CONSTRAINT FK_88F7723B1280B94F');
        $this->addSql('ALTER TABLE element_biblio DROP CONSTRAINT FK_501BB2B19FDDF749');
        $this->addSql('ALTER TABLE traduction_element DROP CONSTRAINT FK_7F7FF2499FDDF749');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8FDEC11ACA');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63FAF0E6016');
        $this->addSql('ALTER TABLE agent_genre DROP CONSTRAINT FK_BAFE1B806DD572C8');
        $this->addSql('ALTER TABLE contient_element DROP CONSTRAINT FK_71BC9231C4ED1CA4');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8F5FF94818');
        $this->addSql('ALTER TABLE sous_region DROP CONSTRAINT FK_DF7D03815FF94818');
        $this->addSql('ALTER TABLE source_langue DROP CONSTRAINT FK_25A85068B560C063');
        $this->addSql('ALTER TABLE agent DROP CONSTRAINT FK_268B9C9DC68BE09C');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63FC68BE09C');
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E39C68BE09C');
        $this->addSql('ALTER TABLE localisation_q_topographie DROP CONSTRAINT FK_C3D418BE9C12BBFD');
        $this->addSql('ALTER TABLE localisation_q_fonction DROP CONSTRAINT FK_F8B0B4679C12BBFD');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73343700E0');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73C3FF2F4A');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73CE19B47A');
        $this->addSql('ALTER TABLE attestation_materiel DROP CONSTRAINT FK_E968255C48095C04');
        $this->addSql('ALTER TABLE agent_nature DROP CONSTRAINT FK_EF3FD58197EF374A');
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E3964A5A8EA');
        $this->addSql('ALTER TABLE contient_element DROP CONSTRAINT FK_71BC9231883FA27F');
        $this->addSql('ALTER TABLE attestation_occasion DROP CONSTRAINT FK_7BDC4928DABD3070');
        $this->addSql('ALTER TABLE attestation_pratique DROP CONSTRAINT FK_F048224C51295B14');
        $this->addSql('ALTER TABLE projet_chercheur DROP CONSTRAINT FK_BE2C7C8476222944');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7376222944');
        $this->addSql('ALTER TABLE localisation_q_fonction DROP CONSTRAINT FK_F8B0B4679E428274');
        $this->addSql('ALTER TABLE localisation_q_topographie DROP CONSTRAINT FK_C3D418BE71B07B4');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F79BDCA9E');
        $this->addSql('ALTER TABLE source_auteur DROP CONSTRAINT FK_B3A594A679BDCA9E');
        $this->addSql('ALTER TABLE source_langue DROP CONSTRAINT FK_25A8506879BDCA9E');
        $this->addSql('ALTER TABLE source_biblio DROP CONSTRAINT FK_6FF39EC379BDCA9E');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8F832FEA1A');
        $this->addSql('ALTER TABLE agent_statut DROP CONSTRAINT FK_BB83A799C3534552');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7381C7EF2');
        $this->addSql('ALTER TABLE titre_auteur DROP CONSTRAINT FK_AFF93D8A11F20684');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F7321FA5D71');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F731E166220');
        $this->addSql('ALTER TABLE attestation DROP CONSTRAINT FK_326EC63F1E25C1F6');
        $this->addSql('ALTER TABLE element DROP CONSTRAINT FK_41405E391E25C1F6');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F731E25C1F6');
        $this->addSql('DROP SEQUENCE activite_agent_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE agent_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE agentivite_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE attestation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE auteur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE biblio_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_materiau_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_occasion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_source_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE categorie_support_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE chercheur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE datation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE entite_politique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE etat_fiche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE formule_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE genre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE genre_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE grande_region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE langue_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE localisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE materiau_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE materiel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nature_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nombre_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE occasion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pratique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE projet_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE q_fonction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE q_topographie_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE source_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sous_region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE statut_affiche_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE titre_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE traduction_element_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_source_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_support_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE verrou_entite_id_seq CASCADE');
        $this->addSql('DROP TABLE activite_agent');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE agent_statut');
        $this->addSql('DROP TABLE agent_nature');
        $this->addSql('DROP TABLE agent_genre');
        $this->addSql('DROP TABLE agent_activite');
        $this->addSql('DROP TABLE agent_agentivite');
        $this->addSql('DROP TABLE agentivite');
        $this->addSql('DROP TABLE attestation');
        $this->addSql('DROP TABLE attestation_pratique');
        $this->addSql('DROP TABLE attestation_occasion');
        $this->addSql('DROP TABLE attestation_materiel');
        $this->addSql('DROP TABLE auteur');
        $this->addSql('DROP TABLE biblio');
        $this->addSql('DROP TABLE categorie_element');
        $this->addSql('DROP TABLE categorie_materiau');
        $this->addSql('DROP TABLE categorie_materiel');
        $this->addSql('DROP TABLE categorie_occasion');
        $this->addSql('DROP TABLE categorie_source');
        $this->addSql('DROP TABLE categorie_support');
        $this->addSql('DROP TABLE chercheur');
        $this->addSql('DROP TABLE contient_element');
        $this->addSql('DROP TABLE datation');
        $this->addSql('DROP TABLE element');
        $this->addSql('DROP TABLE element_categorie');
        $this->addSql('DROP TABLE theonymes_implicites');
        $this->addSql('DROP TABLE theonymes_construits');
        $this->addSql('DROP TABLE element_biblio');
        $this->addSql('DROP TABLE entite_politique');
        $this->addSql('DROP TABLE etat_fiche');
        $this->addSql('DROP TABLE formule');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE genre_element');
        $this->addSql('DROP TABLE grande_region');
        $this->addSql('DROP TABLE langue');
        $this->addSql('DROP TABLE localisation');
        $this->addSql('DROP TABLE localisation_q_topographie');
        $this->addSql('DROP TABLE localisation_q_fonction');
        $this->addSql('DROP TABLE materiau');
        $this->addSql('DROP TABLE materiel');
        $this->addSql('DROP TABLE nature');
        $this->addSql('DROP TABLE nature_element');
        $this->addSql('DROP TABLE nombre_element');
        $this->addSql('DROP TABLE occasion');
        $this->addSql('DROP TABLE pratique');
        $this->addSql('DROP TABLE projet');
        $this->addSql('DROP TABLE projet_chercheur');
        $this->addSql('DROP TABLE q_fonction');
        $this->addSql('DROP TABLE q_topographie');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE source_auteur');
        $this->addSql('DROP TABLE source_langue');
        $this->addSql('DROP TABLE source_biblio');
        $this->addSql('DROP TABLE sous_region');
        $this->addSql('DROP TABLE statut_affiche');
        $this->addSql('DROP TABLE titre');
        $this->addSql('DROP TABLE titre_auteur');
        $this->addSql('DROP TABLE traduction_element');
        $this->addSql('DROP TABLE type_source');
        $this->addSql('DROP TABLE type_support');
        $this->addSql('DROP TABLE verrou_entite');
    }
}
